language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
  - clang
# command to install dependencies
install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install python-rosdep python-rosinstall-generator python-wstool python-rosinstall build-essential
  - sudo rosdep init
  - rosdep update
  - rosinstall_generator ros_comm --rosdistro indigo --deps --wet-only --tar > indigo-ros_comm-wet.rosinstall
  # Make a workspace
  - mkdir -p /tmp/ros_comm_ws/src
  # Add this folder to the workspace
  - ln -s `pwd` /tmp/ros_comm_ws/src/ros_comm
  # Install dependencies
  - cd /tmp/ros_comm_ws
  - wstool init -j8 src indigo-ros_comm-wet.rosinstall
# command to run tests
script:
  - source /opt/ros/indigo/setup.bash
  - cd /tmp/ros_comm_ws
  - catkin_make tests > log.make_tests
  - cd build
  # Manually invoke make, catkin_make
  - make run_tests > log.run_tests || cat log.*
  # Check test results
  - 'python -c "from catkin.test_results import test_results;import sys;sys.exit(sum([v[1] + v[2] for k, v in test_results(\"test_results\").iteritems()]))" || cat log*'
  - 'python -c "from catkin.test_results import test_results;import sys;sys.exit(sum([v[1] + v[2] for k, v in test_results(\"test_results\").iteritems()]))"'
notifications:
  email: false
