version: '2'

services:
  master:
    build: .
    environment:
      - "ROS_SECURITY=ssl"
    command: bash -c "sroscore & rosrun rospy_tutorials listener & rosrun rospy_tutorials talker"

  # resolvable:
  #   image: mgood/resolvable
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock
  #     - /etc/resolv.conf:/tmp/resolv.conf
